spring.application.name=bffmovil
server.port=8092

core.base-url=http://localhost:8090

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit
server.ssl.key-alias=bffmovil
movil.api-key=movil-secreto-2026